version: 0.2

phases:
  install:
    runtime-versions:
      go: 1.20
  build:
    commands:
      - sam build
  post_build:
    commands:
      - sam deploy --no-confirm-changeset --no-fail-on-empty-changeset
