AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  bootstrap
  
  Sample SAM Template for bootstrap

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5

Resources:
  BattleshiperUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: "cognitopool-test"
      Policies:
        PasswordPolicy:
          MinimumLength: 8
      UsernameAttributes:
        - email
      Schema:
        - AttributeDataType: String
          Name: email
          Required: false
  
  BattleshiperUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref BattleshiperUserPool
      ClientName: "cognitopoolclient-test"
      GenerateSecret: false

  BattleshiperApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Auth:
        DefaultAuthorizer: 
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: !GetAtt BattleshiperUserPool.Arn

  BattleshiperProfileFunc:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: api/profile
      Handler: profile
      Runtime: provided.al2023
      Architectures:
        - x86_64
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /profile
            Method: GET
            RestApiId: !Ref: CoreApi
            Auth:
              Authorizer: CognitoAuthorizer
      Environment:
        Variables:
          PARAM1: VALUE

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  ProfileFuncAPI:
    Description: "API Gateway endpoint URL for Prod environment for First Function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  ProfileFunc:
    Description: "First Lambda Function ARN"
    Value: !GetAtt ProfileFunc.Arn
  ProfileFuncIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt ProfileFunc.Arn
