name: publish adapter-battleshiper to package registries

on:
  push:
    branches:
      - main
    paths:
      - "adapter-battleshiper/**"

jobs:
  publish-jsr:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Publish package
        run: |
          cd adapter-battleshiper
          npm ci
          npx jsr publish

  publish-npm:
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          node-version: latest
      - name: publish to npm
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_ACCESS_TOKEN }}" > ~/.npmrc
          cd adapter-battleshiper
          npm ci
          npm publish --access public
